apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: springbootweb-eventlistner
  namespace: pipeline-tutorial
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: springbootweb-trigger
  resources:
    kubernetesResource:
      serviceType: NodePort