apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: springbootweb-trigger
spec:
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: ci-webhook
            secretKey: secret
        - name: "eventTypes"
          value: ["push"]
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: body.ref == 'refs/heads/trigger-config'
  bindings:
    - ref: springbootweb-binding
  template:
    ref: springbootweb-triggertemplate