apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  annotations:
  resourceVersion: '265071629'
  name: gitlab-event-listener-entitlement-service
  uid: 1005d284-a458-4f4a-9b89-290532976d78
  creationTimestamp: '2022-05-25T05:52:34Z'
  generation: 2
  namespace: entitlement
  finalizers:
    - eventlisteners.triggers.tekton.dev
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: pipeline-binding-entitlement-service
      interceptors:
        - params:
            - name: filter
              value: >-
                body.object_attributes.ref  =='develop' &&
                body.object_attributes.status == 'success'
            - name: overlays
              value: null
          ref:
            kind: ClusterInterceptor
            name: cel
        - params:
            - name: secretRef
              value:
                secretKey: secretToken
                secretName: gitlab-interceptors-secret
            - name: eventTypes
              value:
                - Pipeline Hook
          ref:
            kind: ClusterInterceptor
            name: gitlab
      name: pipeline-trigger-service
      template:
        ref: pipeline-template-entitlement-service
