apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: pipeline-tutorial
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi