apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-2 #app CR name
  namespace: argocd-control-plane #argocd instance namespace
spec:
  destination:
    namespace: gitops-demo #namespace where app is deployed
    server: 'https://kubernetes.default.svc'
  source:
    path: app
    repoURL: 'https://github.com/redhat-developer/openshift-gitops-getting-started'
    targetRevision: HEAD
  project: default